# Generated by Django 5.1 on 2024-09-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-distance_in_feet',)},
        ),
        migrations.AddField(
            model_name='competition',
            name='distance_in_feet',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
